### ISSUE TITLE
Can I pr it?

### ISSUE THREAD

**Issue by EpsilonKu** [lmburns/kimbox#7]
Basically I want to make Cmp highlight colors(of course enabling/disabling it on config). Can I add directly to plugin(I'm asking so after denying to not rewrite it)? 
To make menu like this but in kimbox colors:
![173782308-d28623d9-078d-4d15-a5e1-075899fb41ab](https://user-images.githubusercontent.com/63652620/205509346-64b81ea0-9ca1-4e7f-b5ac-35658f6130a4.png)

**Comment by lmburns** [comment]
Sorry for a late reply. Yes you can PR it
